zsh_install: false
homebrew_install: false
dotfiles_link: false

homebrew_installed_packages:
  - automake
  - bash
  - bat
  - cabal-install
  - cmake
  - coreutils
  - lf
  - fd
  - fzf
  - gawk
  - git
  - glib
  - gnutls
  - gobject-introspection
  - gradle
  - haskell-stack
  - jq
  - lazygit
  - luajit
  - luarocks
  - neovim
  - pango
  - pkg-config
  - poppler
  - python@3.9
  - qt
  - ripgrep
  - rust
  - shellcheck
  - tmux
  - tree
  - wget


homebrew_taps:
 -  d12frosted/emacs-plus
 -  hashicorp/tap
 -  homebrew/bundle
 -  homebrew/cask
 -  homebrew/cask-fonts
 -  homebrew/core
 -  homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - font-ubuntu-mono-nerd-font
  - hammerspoon
  - karabiner-elements
  - kitty
  - mactex
